import { MdSentimentVerySatisfied } from "react-icons/md";
import { GiBabyBottle, GiBabyFace } from "react-icons/gi";
import { FaBabyCarriage } from "react-icons/fa";

export const homeData = [
  {
    id: 1,
    name: "Nataniel",
    rating: <MdSentimentVerySatisfied />,
    time: "9 : 18",
    desc: "Nataniel to imię pochodzenia hebrajskiego. Tłumaczyć je można jako 'dany od Boga' lub 'podarowany przez Boga'. Obecnie imię Nataniel nosi 867 Polaków.",
    starring: " Natanielek, Natanielcio, Talutek, Tanieluś.",
    genres: " 24 sierpnia.",
    tags: " Nat King Cole (właśc. Nathaniel Adams Coles, 1919-1965) - amerykański pianista i wokalista jazzowy.",
    cover: "../images/2.jpg",
    video: "../video/1.mp4",
    date: "13.06.2022",
    nameL: " Nathanael, Nathaniel.",
    lang: " po angielsku",
    desc1: "imieniny: 24 lipca, 25 grudnia",
    desc2:
      "Zapis Nataniel to zapis hiszpański i portugalski tego imienia, w tym samym wariancie spotyka się go również w Polsce.",
    desc3:
      "To imię również nosi planetoida odkryta w 1998 r. Pochodzi ona z pasa głównego asteroid, okrążająca Słońce w ciągu 5,3 lat.",
  },
  {
    id: 2,
    name: "Nataniel",
    rating: <MdSentimentVerySatisfied />,
    time: "9 : 41",
    desc: "Znaczeniowo przypomina takie imiona, jak greckie z pochodzenia Teodor czy polskie Bożydar.",
    starring: " Natanieluś, Natanek, Natan, Natuniek, Naćko, Nejt, Tan.",
    genres: "Action",
    tags: " Nathaniel Baldwin – amerykański naukowiec i wynalazca.",
    cover: "../images/5.jpg",
    video: "../video/2.mp4",
    date: "13.06.2022",
    nameL: " Nathaniel.",
    lang: " po niemiecku",
    desc1: "W polszczyźnie przyjęły się dwa imiona biblijne: Natan i Natanael.",
    desc2: "Imię Natan występuje także w Starym Testamencie.",
    desc3:
      "Jezus ujrzał jak Natanael zbliżał się do Niego i mówi o nim: „Patrz, to prawdziwy Izraelita – bez podstępu”.",
  },
  {
    id: 3,
    name: "Nataniel",
    rating: <MdSentimentVerySatisfied />,
    time: "15 : 38",
    desc: "Imieniem Natanael nazywany był w Piśmie Świętym – apostoł Bartłomiej, który na świat przyszedł w pierwszym wieku naszej ery.",
    starring: " Natanuś, Nati, Nelek, Tanek.",
    genres: "Adventures",
    tags: " Nathaniel Hawthorne – pisarz romantyczny, uważany za jednego z największych i najbardziej wpływowych twórców literatury amerykańskiej XIX wieku.",
    cover: "../images/4.jpg",
    video: "../video/9.mp4",
    date: "13.06.2022",
    nameL: " Natanaele.",
    lang: " po włosku",
    desc1:
      "Kult św. Bartłomieja datowany jest od V wieku, kościół łaciński święto Apostoła, od wieku VIII obchodzi 24 sierpnia.",
    desc2:
      "W ikonografii św. Bartłomiej przedstawiany jest w długiej tunice, przepasanej paskiem.",
    desc3:
      "Grecy obchodzą jego uroczystość 11 czerwca, Ormianie 8 grudnia i 25 lutego, Etiopczycy 18 lipca i 20 listopada.",
  },
  {
    id: 4,
    name: "Nataniel",
    rating: <MdSentimentVerySatisfied />,
    time: "12 : 42",
    desc: "Znak zodiaku - Bliźnięta.",
    starring: " Natko, Nateczek, Natkuś, Taniel, Tanielek.",
    genres: "Adventures",
    tags: " Nathaniel Parker – brytyjski aktor teatralny, filmowy i telewizyjny.",
    cover: "../images/3.jpg",
    video: "../video/4.mp4",
    date: "15.06.2022",
    nameL: " Nathanaël.",
    lang: " po łacinie",
    desc1: "Imię Natanael jest dwukrotnie odnotowane w Ewangelii św. Jana.",
    desc2:
      "W Nowym Testamencie mię to nosił jeden z uczniów Jezusa, często utożsamiany z Bartłomiejem Apostołem.",
    desc3:
      "Pojawia się on pod koniec Ewangelii według świętego Jana, jak i w Dziejach Apostolskich.",
  },
];

export const upcome = [
  {
    id: 1,
    cover: "../images/upcome/3.jpg",
    name: "13.06.2022",
    time: "09 : 13",
    link: "//www.pampers.pl/noworodek",
  },
  {
    id: 2,
    cover: "../images/upcome/1.jpg",
    name: "14.06.2022",
    time: "10 : 36",
  },
  {
    id: 3,
    cover: "../images/upcome/5.jpg",
    name: "14.06.2022",
    time: "10 : 36",
  },
  {
    id: 4,
    cover: "../images/upcome/2.jpg",
    name: "14.06.2022",
    time: "10 : 37",
  },
  {
    id: 5,
    cover: "../images/upcome/4.jpg",
    name: "20.06.2022",
    time: "09 : 36",
  },
];

export const latest = [
  {
    id: 1,
    cover: "../images/upcome/6.jpg",
    name: "13.06.2022",
    time: "09 : 13",
  },
  {
    id: 2,
    cover: "../images/upcome/7.jpg",
    name: "14.06.2022",
    time: "10 : 36",
  },
  {
    id: 3,
    cover: "../images/upcome/8.jpg",
    name: "16.06.2022",
    time: "14 : 48",
  },
  {
    id: 4,
    cover: "../images/upcome/9.jpg",
    name: "17.06.2022",
    time: "11 : 19",
  },
  {
    id: 5,
    cover: "../images/upcome/10.jpg",
    name: "23.06.2022",
    time: "10 : 08",
  },
];

export const trending = [
  {
    id: 1,
    name: "Natanek",
    rating: <GiBabyBottle />,
    time: "09 : 28",
    desc: "Śpi ponad 16 godzin na dobę.",
    starring: "Natek, Nat, Natuś",
    genres: "Action",
    tags: "Nathaniel C. Wyeth – amerykański wynalazca, twórca tworzywa PET.",
    cover: "../images/img/1.jpg",
    date: "22.06.2022",
    nameL: " Nathanael.",
    lang: " po grecku",
  },
  {
    id: 2,
    name: "Natanuś",
    rating: <FaBabyCarriage />,
    time: "09 : 28",
    desc: "Bardzo lubi się kąpać. W wodzie uśmiecha się.",
    starring: "Natusiek, Natuniek, Nejtan",
    genres: "Adventures",
    tags: "Nathaniel Rateliff – amerykański piosenkarz.",
    cover: "../images/img/2.jpg",
    date: "22.06.2022",
    nameL: " Nathanaël.",
    lang: " po francusku",
  },
  {
    id: 3,
    name: "Nateczek",
    rating: <GiBabyFace />,
    time: "09 : 36",
    desc: "Umie ssać pierś przez nakładkę. Mleczko mamy bardzo mu smakuje.",
    starring: "Nielek, Tal, Talek",
    genres: "Adventures",
    tags: "Nathaniel Clyne – angielski piłkarz.",
    cover: "../images/img/3.jpg",
    date: "20.06.2022",
    nameL: " Natanael.",
    lang: " po czesku",
  },
];
export const recommended = [
  {
    id: 1,
    cover: "../images/6.jpg",
    name: "Już jestem w ubranku",
    time: "15 : 14",
    date: "23.06.2022",
  },
  {
    id: 2,
    cover: "../images/upcome/14.jpg",
    name: "Razem z tatą",
    time: "10 : 51",
  },
  {
    id: 3,
    cover: "../images/upcome/16.jpg",
    name: "Ja i tata",
    time: "10 : 51",
  },

  {
    id: 4,
    cover: "../images/upcome/17.jpg",
    name: "Duma taty",
    time: "10 : 51",
  },
  {
    id: 5,
    cover: "../images/upcome/13.jpg",
    name: "Kolorowy sen",
    time: "10 : 51",
  },
  {
    id: 6,
    cover: "../images/upcome/15.jpg",
    name: "W całej okazałości",
    time: "10 : 51",
  },
  {
    id: 7,
    cover: "../images/upcome/18.jpg",
    name: "Kto mnie budzi?",
    time: "10 : 51",
  },
  {
    id: 8,
    cover: "../images/rec/1.jpg",
    name: "W wytwornej czapeczce",
    time: "10 : 51",
  },
  {
    id: 9,
    cover: "../images/rec/3.jpg",
    name: "W wózku z maskotką",
    time: "15 : 35",
  },
  {
    id: 10,
    cover: "../images/rec/2.jpg",
    name: "Myślę, więc jestem",
    time: "10 : 08",
  },
  {
    id: 11,
    cover: "../images/rec/11.jpg",
    name: "W fotelu z mamą",
    time: "14 : 06",
  },
  {
    id: 12,
    cover: "../images/upcome/11.jpg",
    name: "Idzie lato",
    time: "20 : 44",
  },
  {
    id: 13,
    cover: "../images/upcome/12.jpg",
    name: "Nie przegrzewam się",
    time: "20 : 47",
  },
  {
    id: 14,
    cover: "../images/upcome/19.jpg",
    name: "Swiat jest ciekawy",
    time: "19 : 38",
  },
  {
    id: 15,
    cover: "../images/upcome/20.jpg",
    name: "Jestem tutaj",
    time: "19 : 38",
  },
  {
    id: 16,
    cover: "../images/upcome/21.jpg",
    name: "W body",
    time: "19 : 06",
  },
  {
    id: 17,
    cover: "../images/upcome/22.jpg",
    name: "W łóżeczku",
    time: "20 : 26",
  },
  {
    id: 18,
    cover: "../images/upcome/23.jpg",
    name: "Blisko mamy i taty",
    time: "20 : 26",
  },
  {
    id: 19,
    cover: "../images/upcome/24.jpg",
    name: "Z elektronicznym misiem",
    time: "17 : 56",
  },
  {
    id: 21,
    cover: "../images/upcome/25.jpg",
    name: "Miś czuwa, gdy ja śpię",
    time: "14 : 44",
  },
  {
    id: 22,
    cover: "../images/upcome/28.jpg",
    name: "Trochę na boczku",
    time: "17 : 07",
  },
  {
    id: 23,
    cover: "../images/upcome/26.jpg",
    name: "Rozglądam się po pokoju",
    time: "15 : 07",
  },
  {
    id: 24,
    cover: "../images/upcome/27.jpg",
    name: "Nie zawsze tylko śpię",
    time: "15 : 07",
  },
  {
    id: 25,
    cover: "../images/upcome/29.jpg",
    name: "Na pajacyka",
    time: "10 : 23",
  },
  {
    id: 26,
    cover: "../images/upcome/30.jpg",
    name: "Znowu zmorzył mnie sen",
    time: "10 : 21",
  },
  {
    id: 27,
    cover: "../images/upcome/31.jpg",
    name: "Teraz na drugim boczku",
    time: "19 : 37",
  },
  {
    id: 28,
    cover: "../images/upcome/32.jpg",
    name: "Bez smoczka nie dam rady",
    time: "19 : 08",
  },
  {
    id: 28,
    cover: "../images/upcome/36.jpg",
    name: "Nie ma to jak dobrze się wyspać",
    time: "20 : 38",
  },
];
